services:
  db:
    container_name: iots_postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_podaci:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mreza
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  DataManager:
    container_name: iots_data_manager
    image: data_manager
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mreza
    ports:
      - 8080:8080

networks:
  mreza:
    driver: bridge
