services:
  db:
    container_name: iots_postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_podaci:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mreza
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d test_db"]
      interval: 3s
      timeout: 3s
      retries: 5

  datamanager:
    container_name: iots_data_manager
    build: ./DataManager
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mreza
    ports:
      - 5050:5050
    #healthcheck:
     # test: ["CMD", "bash", "health.sh"]
      #interval: 5s
      #timeout: 5s
      #retries: 5
      #start_period: 10s

  gateway:
    container_name: iots_gateway
    build: ./Gateway
    depends_on:
      - datamanager
        #condition: service_healthy
    networks:
      - mreza
    ports:
      - 8080:8080

networks:
  mreza:
    driver: bridge
